jobs:
- name: show-crendetials-job
  plan:
  - task: show-crendetials-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: echo
        args:
          - ((username))
          - ((password))
      params:
        USER_NAME: ((username))
        PASSWD: ((password))