resources:
  - name: concourse-learning
    type: git
    icon: github
    source:
      uri: https://github.com/prashant887/concourse-learning.git
      branch: dev-branch
jobs:
- name: job-concourse-complie
  public: true
  plan:
  - get: concourse-learning
    trigger: true
  - task: create-go-exe
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: golang }
      inputs:
        - name: concourse-learning
      outputs:
      - name: exec-dir
      run:
        #dir: concourse-learning
        path: sh
        args:
          - -exc
          -  |
             go build -o exec-dir concourse-learning/concourse-complie/hello-word.go

  - task: exec-go-exec
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: alpine }
      inputs:
      - name: exec-dir
      run:
        dir: exec-dir
        path: sh
        args:
          - -exc
          - |
            ./hello-word