jobs:
- name: job-ipop-files
  public: true
  plan:
  - task: create-some-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: alpine }
      outputs:
      - name: some-files
      run:
        dir: some-files
        path: sh
        args:
          - -exc
          -  |
             pwd
             echo "Hello From Input $(hostname) : $(date)" > outfile.txt
             ls -lrt outfile.txt
             cat outfile.txt

  - task: show-some-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: alpine }
      inputs:
      - name: some-files
      run:
        dir: some-files
        path: sh
        args:
          - -exc
          - |
            pwd
            ls -lrt
            ls -lrt outfile.txt
            cat outfile.txt